### ISSUE TITLE
Setup failed !

### ISSUE THREAD

**Issue by gugansankar** [umrum/umrum#63]
I'm unable to install umrum in my lab setup. I followed the steps mentioned in README.md file.

I tried both azk and manual installation.But both failed with same error message.

OS: Ubuntu 16.04.1 LTS

Error message:

```
root@ubuntu:~# azk shell umrum -c 'npm run watch-webpack'
azk: Manifest file (`Azkfile.js`) was not found at `/root` (see more at http://docs.azk.io/en/azkfilejs/)
root@ubuntu:~# cd umrum/
root@ubuntu:~/umrum# azk shell umrum -c 'npm run watch-webpack'
npm info it worked if it ends with ok
npm info using npm@3.10.8
npm info using node@v6.9.1
npm info lifecycle UMRUM@0.0.0~prewatch-webpack: UMRUM@0.0.0
npm info lifecycle UMRUM@0.0.0~watch-webpack: UMRUM@0.0.0

> UMRUM@0.0.0 watch-webpack /azk/umrum
> webpack-dev-server --history-api-fallback --hot --inline --progress --host $WEBPACK_HOST --port $WEBPACK_PORT

 40% 2/4 build modulesevents.js:160
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND webpack-umrum.dev.azk.io
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)

npm info lifecycle UMRUM@0.0.0~watch-webpack: Failed to exec watch-webpack script
npm ERR! Linux 4.4.0-31-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "watch-webpack"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! UMRUM@0.0.0 watch-webpack: `webpack-dev-server --history-api-fallback --hot --inline --progress --host $WEBPACK_HOST --port $WEBPACK_PORT`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the UMRUM@0.0.0 watch-webpack script 'webpack-dev-server --history-api-fallback --hot --inline --progress --host $WEBPACK_HOST --port $WEBPACK_PORT'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the UMRUM package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --history-api-fallback --hot --inline --progress --host $WEBPACK_HOST --port $WEBPACK_PORT
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs UMRUM
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls UMRUM
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /azk/umrum/npm-debug.log

```

**Comment by rafaelverger** [comment]
Hi @gugansankar , sorry for the delay and the trouble trying to start up the project... I would dig into this issue this week and hope I can fix it for you...
